### ISSUE TITLE
Apply "caption" text style to tags

### ISSUE THREAD

**Issue by LenaNguyen** [uwblueprint/sistering#141]
Tags should have the `caption` textStyle applied to them by default through the theme. This textStyle is defined in `frontend\src\theme\index.ts` . 

The text styling was added [here](https://github.com/uwblueprint/sistering/pull/124/files) and additional styling was added in [this pr](https://github.com/uwblueprint/sistering/pull/133). At the time, the tag text was correct, but now it doesn't seem to be applying anymore. For example, the font-weight should be 'normal' but it's getting applied as 'medium'.

**Comment by sherryhli** [comment]
> At the time, the tag text was correct, but now it doesn't seem to be applying anymore.

Is it somehow being overriden by another property? I think part of this ticket's work could involve investigating this. Setting "caption" as the default property is more preferable than specifying textStyle="caption" each time we use a tag.
