### ISSUE TITLE
Create empty posting cards

### ISSUE THREAD

**Issue by JoshuaYe** [uwblueprint/sistering#160]
### Summary and Background
Update this ticket with new UI: https://app.zenhub.com/workspaces/sistering-614f8dad6afeb8001d428787/issues/uwblueprint/sistering/82

### Solution (Core Elements)
Create an empty event card to be displayed when there are no events available. Create an empty volunteer opportunity card to be displayed when there are no volunteer opportunities available.

Make any updates to a filled event card. Note that they should disappear for a volunteer after the deadline.

### Mockups
![7.png](https://images.zenhubusercontent.com/61d64353fa88e90a47f942bc/7f624130-2d56-451b-83b0-bde72d300da6)

Other designs:
- https://www.figma.com/file/KWaJRNJcOiW8ThZJ8Sl6On/Sistering-%2F-Volunteer-Experience?node-id=157%3A3123

### Technical
Create an `EmptyCard.tsx` component in `frontend\src\components\common` that takes a prop like `emptyMessage` as a string which will be the message that is displayed in the component. 

Add the copy to `frontend\src\constants\Copy.ts` with the prefix `VOLUNTEER_POSTINGS_` 

## Dev Notes
* Chakra [Box](https://chakra-ui.com/docs/layout/box)

**Comment by sherryhli** [comment]
I believe @Boyazhang1 has already completed this task (#149)
