### ISSUE TITLE
Schedule Review Table Data Fetch

### ISSUE THREAD

**Issue by LenaNguyen** [uwblueprint/sistering#162]
Fetch the data needed for the Schedule Review Table and display it in the UI made in #158.

You will need to query for `shiftSignups` for a given posting, where the status is `SignupStatus.CONFIRMED`

**Comment by sherryhli** [comment]
**Additional requirements discussed during the March 20th work session:**

* A new `getShiftSignupsWithVolunteerForPosting` GraphQL query defined in `shiftSignupResolvers`
* A new `getShiftSignupsWithVolunteerForPosting` method defined in `shiftSignupService` with signature:
```ts
getShiftSignupsWithVolunteerForPosting(postingId: string): ShiftSignupWithVolunteerResponseDTO[]
```
* `ShiftSignupWithVolunteerResponseDTO` is a new custom type consisting of all fields in `ShiftSignupResponseDTO` as well as a nested volunteer object of type `VolunteerUserResponseDTO`
* The data fetch is executed from the admin schedule page created in #194
