### ISSUE TITLE
Side panel

### ISSUE THREAD

**Issue by JoshuaYe** [uwblueprint/sistering#176]
### Summary and Background
Side panel component contains basic structure and header of side panel.

### User Story
As an Admin, I want a side panel to view more information about a day or volunteer.

### Solution (Core Elements)
Create side panel component.

Side panel header displays selected date.

Side panel body should be filled with content from other tickets:
- Edit volunteers #172
- Empty shifts #171
- Volunteer profile #169 (not included in this ticket and soft launch)

### Mockups
Only side panel structure and header (not body):
![2.png](https://images.zenhubusercontent.com/61d64353fa88e90a47f942bc/ec4acb27-358d-406c-9c55-270bff7ecf86)

Other designs: https://www.figma.com/file/TWJTNWjK75A6VgSisySTLe/Sistering-%2F-Admin-Experience?node-id=888%3A8374

 ### Technical
* Create a new component in /components/admin/schedule called `ScheduleSidePanel.tsx`
* Display the component in `AdminSchedulePage.tsx`.
* If there are no shifts, display Empty shifts in the side panel
* If there are shifts, display #172 in the side panel

**Comment by LenaNguyen** [comment]
Not included in this ticket, but adding here to remember later, when we display #171, we ill use an enum containing SCHEDULE_VOLUNTEER and VOLUNTEER_INFO to navigate between scheduling a volunteer and viewing the volunteer details.
