### ISSUE TITLE
Integrate Google Analytics and Hotjar

### ISSUE THREAD

**Issue by JoshuaYe** [uwblueprint/sistering#298]
### Context

Product @ Blueprint doesn't really use data to make decisions because of the shortness of projects and handoffs. Thus, I thought it'd be cool to break that trend starting with Sistering's soft launch! By integrating Google Analytics and Hotjar, I'm hoping to get some insights for how we can improve next term. 😁

### Google Analytics

Integrate Google Analytics into https://sistering-dev.web.app/ for soft launch. Contact Joshua to verify it is working, since he owns the account.

Instructions: https://chartio.com/learn/marketing-analytics/how-to-add-google-analytics-tracking-to-a-website/ (Google Analytics Tracking Code)

Code:
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-DF2BP4T8YQ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-DF2BP4T8YQ');
</script>
```

### Hotjar

Integrate Hotjar into all Sistering pages in https://sistering-dev.web.app/ for soft launch. Contact Joshua to verify it is working, since he owns the account.

Instructions: https://help.hotjar.com/hc/en-us/articles/115009336727-How-to-Install-your-Hotjar-Tracking-Code

Code:
```
<!-- Hotjar Tracking Code for my site -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:2949419,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
```

**Comment by MatoPlus** [comment]
TODO: Still need to update vault once server is up.

**Comment by MatoPlus** [comment]
Hotjar is hooked up but it seems like GA is not any analytics. I think Hotjar gives us sufficient analytics.
