### ISSUE TITLE
Create placeholder for profile photo + buttons for uploading/removing a profile photo

### ISSUE THREAD

**Issue by neelismail01** [uwblueprint/sistering#353]
## Summary and Background
Create components for uploading and removing a profile picture as well as a placeholder for a user's profile picture. Step needed for #341.

## Technical
* In the component `frontend/src/components/pages/NewAccountPage.tsx`, create buttons for uploading and removing a photo
* Create the placeholder (and its label) for the profile photo

Refer to the screenshot below for design requirements.

![image.png](https://images.zenhubusercontent.com/6282fded18ada3180b3a0073/8f730d75-2082-4276-89db-8f669d1232de)

**Comment by MatoPlus** [comment]
Dupe, see updated #360
