### ISSUE TITLE
Remove user modal

### ISSUE THREAD

**Issue by JoshuaYe** [uwblueprint/sistering#400]
### Summary and Background
Remove user modal confirms to the super admin whether they want to remove a user from the platform.

### User Story
As a Super Admin, I want a final confirmation before removing a user from the platform.

### Solution (Core Elements)
Create remove user modal.

Clicking 'Cancel' makes the modal disappear.

Clicking 'Send Invite' removes the user from the platform and makes the modal disappear. The user should not appear in user management anymore.

### Mockups
![image.png](https://images.zenhubusercontent.com/61d64353fa88e90a47f942bc/62161d2b-1179-4a85-a72f-bf3c9cd72d54)

Other designs: 
https://www.figma.com/file/TWJTNWjK75A6VgSisySTLe/Sistering-%2F-Admin-Experience?node-id=1643%3A48816

Technical:
- Tweak `frontend/src/components/admin/DeleteModal.tsx` to accept a `confirmText` prop and use it to determine the text disabled for the delete button in the delete modal

**Comment by lambo-liu** [comment]
> Clicking 'Send Invite' removes the user from the platform and makes the modal disappear. The user should not appear in user management anymore.

We should change the description on this right?
