### ISSUE TITLE
migrate volunteer DoB and pronouns to user schema

### ISSUE THREAD

**Issue by MatoPlus** [uwblueprint/sistering#503]
- update all types and code across backend and frontend
- for forms, make sure we are now submitting DoB and pronouns to the create user queries
- As part of this ticket, please ensure that that the edit account pages `edit-account` are all updated and functional when querying for data

**Comment by eevanwong** [comment]
Note: 
- After some discussion, its ok if this requires a db reset (for now), so  I can manipulate the prisma schema directly and just change the seeding (in the future this will need to be a bit different, but its ok for now).
