### ISSUE TITLE
Employee Edit Profile Page Doesn't work

### ISSUE THREAD

**Issue by MatoPlus** [uwblueprint/sistering#562]
![image.png](https://images.zenhubusercontent.com/61e48df22f0c8deac5a38226/ce6dc5c4-6792-4461-a2c2-1b103ffd6574)

**Comment by eevanwong** [comment]
Strangely enough, the sistering logo is not clickable either. Network doesnt really pop up or anything like that.

**Comment by eevanwong** [comment]
I can no longer replicate this bug... this may have been due to having originally been a volunteer account, turned to admin.
