### ISSUE TITLE
Remove user verification email from being sent

### ISSUE THREAD

**Issue by MatoPlus** [uwblueprint/sistering#570]
Role: All

Route: User Management Invite Flow

Desc: After creating an account from an invite, users are then sent an email verification email. This has been deprecated and we should turn off user verification emails

**Comment by lambo-liu** [comment]
When the volunteer does not have branches assigned to them, the UI for the side panel displays properly (buttons fit on screen)

![Screen Shot 2022-08-08 at 7.29.09 PM.png](https://images.zenhubusercontent.com/614fa42383cf646092757b09/1152ea52-9cf0-4490-8df8-14b0f64093a5)
