### ISSUE TITLE
Admin Posting card volunteer plural on singular count

### ISSUE THREAD

**Issue by MatoPlus** [uwblueprint/sistering#571]
Role: Super Admin/Admin

Route: /admin

Steps to Reproduce: Create posting with 1 volunteer capacity

![image.png](https://images.zenhubusercontent.com/61e48df22f0c8deac5a38226/ecb3ace3-e796-4d64-bb16-7a4e04cebe7a)

Expected: Should be "1 volunteer" not "volunteers"

**Comment by sherryhli** [comment]
Closed via #596
