### ISSUE TITLE
Admin "Select Shift Times" Calendar - Research

### ISSUE THREAD

**Issue by LenaNguyen** [uwblueprint/sistering#86]
## User Story and Context

As an admin (Sistering employee), I need to add the specific timeslots for shifts so volunteers can identify if they are available for the opportunity.

### Product
Please see #42. Note that the attached design in #42 is outdated, here is a more recent version, however you should confirm with @amandatdu before proceeding.

**This ticket covers the parts enclosed in the red rectangle only**:
![image.png](https://images.zenhubusercontent.com/61cddbd0ece8ea4c2aab2823/4312c3a0-aa92-46cc-bbe2-a27a5e62b76f)

**Figma link:** https://www.figma.com/file/TWJTNWjK75A6VgSisySTLe/Admin-Experience?node-id=186%3A2199

Please confirm with @amandatdu on which designs to use.

### Technical
* Create both a form component (in `PostingShiftsCalendar.tsx` under `frontend/src/components/admin/posting`)

## Dev Notes
This ticket will require some investigation.

**react-grid-layout:**
https://www.npmjs.com/package/react-grid-layout

**Comment by lambo-liu** [comment]
Quick summary on my research findings:

We should leverage FullCalendar for its simple implementation. FullCalendar has many built in features such as drag and drop event blocks, clicking on the calendar UI to create a new event, and dragging the ends of existing events to make them longer/shorter. By locking the calendar on weekly view and disabling navigation, we can get a lo-fi looking UI that has the same structure as the Figma designs.

In terms of design, FullCalendar provides limited support to change the background and text colours. Other CSS customizations will require directly overriding the CSS classes, as mentioned here: https://fullcalendar.io/docs/css-customization.

FullCalendar has pretty decent documentation (aside from not having a search lol), and I'd recommend us using it moving forward. My current demo example is on the lambert/implement-calendar-ui branch and can be seen by navigating to the home page.

**Comment by sherryhli** [comment]
@lambo-liu Awesome, thanks for documenting these findings! 💯
